Repository ostis-ai/sc-machine, pull requests merged in 2022-10, with the labels that each got.

#172 [ci] Add ci for docker run on ubuntu-latest
  .github/workflows/docker.yml
  .github/workflows/main.yml
  docker-compose.yml
  sc-tools/sc-server/src/main.cpp
  scripts/docker_entrypoint.sh
  scripts/healthcheck.py
Labels: 0.7.0, ci

#174 [memory][dictionary] Find links by substring, not by substring prefix, implement find strings by substring, add remove links contents
  docs/changelog.md
  docs/sc-network/sc_json.g4
  docs/storage/sc-dictionary.md
  sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.c
  sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary.h
  sc-memory/sc-core/sc-store/sc-container/sc-dictionary/sc_dictionary_private.h
  sc-memory/sc-core/sc-store/sc-container/sc-list/sc_list.c
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage_private.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage_builder.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.h
  sc-memory/sc-core/sc-store/sc_storage.c
  sc-memory/sc-core/sc-store/sc_storage.h
  sc-memory/sc-core/sc_memory.c
  sc-memory/sc-core/sc_memory.h
  sc-memory/sc-memory/sc_memory.cpp
  sc-memory/sc-memory/sc_memory.hpp
  sc-memory/tests/sc-memory/common/sc-link.cpp
  sc-memory/tests/sc-memory/containers/sc-dictionary.cpp
  sc-tools/sc-builder/src/scs_translator.cpp
  sc-tools/sc-config-utils/sc-config/sc_config.c
  sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_json_action.hpp
  sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_keynodes_json_action.hpp
  sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp
  sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_make_template_json_action.hpp
  sc-tools/sc-server/tests/api/units/test_base.cpp
Labels: 0.7.0, sc-memory, file system

#179 [memory][fs-storage] Search by substring as prefix if length < 4
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.c
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_fs_storage.h
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.cpp
  sc-memory/sc-core/sc-store/sc-fs-storage/sc_rocksdb_fs_storage.h
  sc-memory/sc-core/sc-store/sc_storage.c
  sc-memory/sc-core/sc-store/sc_storage.h
  sc-memory/sc-core/sc_memory.c
  sc-memory/sc-core/sc_memory.h
  sc-memory/sc-memory/sc_memory.cpp
  sc-memory/sc-memory/sc_memory.hpp
  sc-memory/tests/sc-memory/common/sc-link.cpp
  sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_handle_link_content_json_action.hpp
Labels: 0.7.0, API, file system

#147 Release 0.7.0-Rebirth
  .gitattributes
  .github/workflows/style.yml
  CMakeLists.txt
  README.md
  docs/build/cmake-flags.md
  docs/build/osx-build.md
  docs/changelog.md
  docs/index.md
  mkdocs.yml
  scripts/clang/check_formatting.sh
  scripts/clang/format_code.sh
  scripts/install_deps_macOS.sh
  scripts/install_deps_ubuntu.sh
Labels: 0.7.0, build, cmake

#182 [ci] Fix Docker push tags
  .github/workflows/release.yml
Labels: bug, 0.7.0, ci
