Repository ostis-ai/sc-machine, pull requests merged in 2025-01, with the labels that each got.

#434 [memory][scs][parser] Don't generate arcs from sc-element classes
  docs/changelog.md
  sc-memory/sc-memory/include/sc-memory/scs/scs_parser.hpp
  sc-memory/sc-memory/include/sc-memory/scs/scs_types.hpp
  sc-memory/sc-memory/src/sc_scs_helper.cpp
  sc-memory/sc-memory/src/sc_template_scs.cpp
  sc-memory/sc-memory/src/scs/scs.g4
  sc-memory/sc-memory/src/scs/scs_parser.cpp
  sc-memory/sc-memory/src/scs/scs_types.cpp
  sc-memory/sc-memory/tests/sc-memory/units/common/test_sc_type.cpp
  sc-memory/sc-memory/tests/sc-memory/units/scs-helper/test_scs_helper.cpp
  sc-memory/sc-memory/tests/sc-memory/units/templates/test_sc_templates_scs.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_alias.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_common.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_1.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_2.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_3.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_4.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_5.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_level_6.cpp
  sc-memory/sc-memory/tests/scs/units/test_scs_utils.hpp
  sc-tools/sc-builder/include/sc-builder/scs_loader.hpp
  sc-tools/sc-builder/src/scs_loader.cpp
  sc-tools/sc-builder/src/scs_translator.cpp
Labels: scs, sc-template-build, 0.10.0

#458 Update conan cd and docs
  .github/workflows/release.yml
  CMakeLists.txt
  COPYING.MIT
  docs/build/build_system.md
  docs/quick_start.md
Labels: documentation, ci, 0.10.0

#453 [tools][server] Environment variables for sc-server host and port
  docker-compose.yml
  docs/changelog.md
  docs/sc-tools/sc_machine.md
  sc-tools/sc-machine-runner/src/sc_machine_runner.cpp
  sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
  sc-tools/sc-server/src/sc-server-impl/sc_server.hpp
  sc-tools/sc-server/src/sc_server_module.cpp
  sc-tools/sc-server/tests/units/api/test_connection.cpp
Labels: sc-server, 0.10.0

#463 [ci] Fix uploading artifacts for release
  .github/workflows/release.yml
Labels: documentation, ci, 0.10.0

#462 [docs] Add installing pipx and conan into quick start for users
  docs/build/build_system.md
  docs/build/quick_start.md
  docs/quick_start.md
Labels: bug, documentation, 0.10.0

#464 [docs] Release 0.10.0
  docs/changelog.md
Labels: 0.10.0

#465 Don't replace agent logs in migration
  docs/changelog.md
  docs/sc-tools/migrate_to_new_agent_api.md
  scripts/migration/migrate_to_new_agent_api.jar
Labels: bug, 0.10.1

#467 [docs] Fix typos in C++ Simple Guide for Implementing Agent and User permissions API
  docs/changelog.md
  docs/sc-memory/api/cpp/extended/permissions_api.md
  docs/sc-memory/api/cpp/guides/simple_guide_for_implementing_agent.md
Labels: documentation, enhancement, 0.10.1

#468 [ci] Add ellipsis.yaml
  docs/changelog.md
  ellipsis.yaml
Labels: enhancement, ci, 0.10.1

#466 [build][conan] Optimize using libxml2 dependency
  conanfile.py
  docs/changelog.md
  sc-tools/sc-builder/CMakeLists.txt
  sc-tools/sc-builder/src/gwf_parser.hpp
  sc-tools/sc-builder/src/gwf_translator_constants.hpp
Labels: enhancement, build, 0.10.1

#469 [docs] Use Latin `c` instead of Cyrillic `с`
  docs/sc-memory/api/cpp/guides/simple_guide_for_implementing_agent.md
Labels: documentation, enhancement, 0.10.1
